### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by PieterAelse** [sbondini/Xamarin.LocalNotifications#4]
I'm not able to get this plugin working.. I've done:
-Install package in my PCL
-Install package in my .Droid project
-Added the receiver to my manifest at Properties/AndroidManifest.xml
-Copied your demo code (excluding the cancel)
-Run/debug

But no notification is shown. No error is shown or logged. No crash. 

Am I missing something or doing something wrong?

(PS: cannot try other platforms because I'm using Xamarin Studio on Windows..)

**Comment by ilchenkob** [comment]
@PieterAelse 
I fixed some issues. You can download sample project to see how to use it: [Android sample](https://github.com/B1naryStudio/Xamarin.LocalNotifications/tree/master/Samples/LocalNotifications.Samples.Droid)
