### ISSUE TITLE
iOS  - crashes on LocalNotifier.Notify()

### ISSUE THREAD

**Issue by catlin0123** [sbondini/Xamarin.LocalNotifications#5]
When running on iOS I get an exception when I call LocalNotifier.Notify 

System.ExecutionEngineException: Attempting to JIT compile method 'LocalNotifications.Plugin.LocalNotifier:createNativeNotification (LocalNotifications.Plugin.Abstractions.LocalNotification)' while running with --aot-only. See http://docs.xamarin.com/ios/about/limitations for more information.

The code to reproduce is written in the AppDelegate in FinishLaunching. 

```
var notifier = new LocalNotifer();
notifer.Notify(new LocalNotification
{
    Title = "Title",
    Text = "Text",
    Id = "1",
    NotifyTime = DateTime.Now,
}
```

This same code works just find on android.

**Comment by KathirveluM** [comment]
Hi,
We are too facing the same issue while running the code " notifier.Notify(notification);" from PCL Project in iOS Platform and the same is working fine in Android Platform. 

Do we need to include any other parameters in AppDelegate Class?

Exception: 
{System.MissingMethodException: Method 'NSDate.op_Implicit' not found.  at LocalNotifications.Plugin.LocalNotifier.Notify (LocalNotifications.Plugin.Abstractions.LocalNotification notification) [0x00000] in <filename unknown>:0   at Mobile.View.SamplePage..ctor () [0x0004a] in D:\Kathir\Mobile\Mobile\View\SamplePage.xaml.cs:38 }

Note: 
We have followed only the below mentioned instructions in the link.
https://github.com/B1naryStudio/Xamarin.LocalNotifications

**Comment by ilchenkob** [comment]
@catlin0123
I fixed this bug. Also you can find the working sample of using our plugin: [iOS sample](https://github.com/B1naryStudio/Xamarin.LocalNotifications/tree/master/Samples/LocalNotifications.Samples.iOS)
