### ISSUE TITLE
Xamarin.Forms

### ISSUE THREAD

**Issue by jerone** [sbondini/Xamarin.LocalNotifications#7]
Does this package work with Xamarin.Forms?

**Comment by ilchenkob** [comment]
@jerone 
Yes, it does. I added sample project: [Xamarin.Forms sample](https://github.com/B1naryStudio/Xamarin.LocalNotifications/tree/master/Samples/LocalNotifications.Samples.Forms)

**Comment by sagarmp02** [comment]
how to fire notifications from MainPage of xamarin.forms project? using this plugin?
